### ISSUE TITLE
Page with login and password field

### ISSUE THREAD

**Issue by Marcin3** [pwiklowski/darkroom#1]
As a user after open  a page I want to see a field to write login and password.
Name of id:

- login field = "login_field"
- password field = "password_field"
- login button = "login_button"

**Comment by mbelicki** [comment]
+1, this is a crtitical enhancement.

**Comment by pwiklowski** [comment]
Application uses 3rd party services(Google, Facebook and Twitter) to authenticate - login and password are not needed so there will be no login and password inputs.
